# .streamlit/secrets.toml
ADMIN_PWD = "admin"

# data-limite para permitir reserva de tema APENAS com >=5 membros
# (formato ISO 8601; ajuste o fuso se quiser)
RESERVE_DEADLINE = "2025-03-30T23:59:00-03:00"

# quantidade mínima de membros para reservar tema ANTES da data-limite
MIN_MEMBERS_BEFORE_DEADLINE = 5

# depois da data-limite, manter a mesma exigência (ou reduzir para 4)
MIN_MEMBERS_AFTER_DEADLINE = 3
