ADMIN_PWD = "admin"

---

#### f) (opcional) `.gitignore`


---

### 3) Rodar no **Streamlit Cloud** (um clique)
1. Acesse https://share.streamlit.io (ou "Deploy app" no perfil).  
2. Conecte sua conta GitHub e escolha o repositório.  
3. **Main file path:** `app.py`  
4. Deploy.

Pronto: você ganha um **link permanente** para o app.  
Os usuários baixam/exportam arquivos **direto do app**, sem passar por links do chat.

---

Se preferir, posso revisar seu repositório depois que você criar (me diga o nome exato) e te digo se algo faltou ou se há algum erro de indentação/arquivo.
