# Obrigatórios
ADMIN_EMAIL = "rsaldanha@pucsp.br"
ADMIN_PIN   = "8722"

# Opcional (para replicar arquivos no SharePoint – client credentials)
TENANT_ID      = "316869c0-3501-410a-ab41-8904bd31168e"
CLIENT_ID      = "c5bb79ff-1f96-49b9-b158-7d2a74940a2e"
CLIENT_SECRET  = "COLOQUE_O_SECRET_AQUI"
SP_SITE_URL    = "https://sidera.sharepoint.com/sites/PUC-Submissoes-Industrial"
SP_DRIVE_NAME  = "Documentos Compartilhados"
SP_BASE_FOLDER = "Submissoes_2025_2"   # pasta raiz onde salvaremos
